import React, { useState } from 'react';
import logo from './btc-logo.png';
import './App.css';
import GameInterface from './pages/gameInterface';
import GameRules from './components/GameRules';
import { CiCircleInfo } from "react-icons/ci";
import styled from 'styled-components';
import { Amplify } from 'aws-amplify';
import awsconfig from './aws-exports'; // The configuration file generated by Amplify

Amplify.configure(awsconfig);

const StyledInfo = styled(CiCircleInfo)`
  font-size: 2rem;
  font-weight: bold;
  color: darkblue;
  cursor: pointer;
`

function App() {
  const [showRules, setShowRules] = useState(false);

  return (
    <div className="App">
      <h1 className="title">Bitcoin Price Guessing Game
      <StyledInfo onClick={() => setShowRules(true)} />
      </h1>
      <GameInterface />
      <GameRules showRules={showRules} onClose={() => setShowRules(false)}/>
    </div>
  );
}

export default App;
